Repository DistroAV/DistroAV, pull requests merged in 2024-07, with the labels that each got.

#1041 Update libndi-get.sh
  CI/libndi-get.sh
Labels: linux (supported), Installation

#1032 CI: Remove quotes '' from receipt and version strings
  cmake/macos/resources/create-package.cmake.in
Labels: obs-plugintemplate

#1056 4.14.1: Minor release to real-world test Update **BEFORE** bigger 6.0.0 release
  buildspec.json
Labels: Seeking Testers, alpha-rc-release
